name: ukan-cbam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit
  - pip
  - pip:
    - timm
    - fvcore
    - albumentations
    - opencv-python
    - pillow
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - tensorboard
    - wandb
    - pyyaml
    - tqdm
    - scikit-learn
    - scikit-image
    - pandas
